#!/usr/bin/env bash

set -e

THIS_DOCKER="$(realpath "$0")"
NEXT_DOCKER="$(which --all docker | grep --after-context=1 "$THIS_DOCKER" | tail -1)"
DEFAULT_COMMAND='help'

function main {
  local subcommand args
  subcommand="$1"
  args=("${@:2}")
  if [[ "$subcommand" == '' ]]; then
    subcommand="$DEFAULT_COMMAND"
  fi
  if is_override_subcommand "$subcommand"; then
    if contains_help_flag "${args[@]}"; then
      "help_long_$subcommand" "${args[@]}"
    else
      "override_$subcommand" "${args[@]}"
    fi
  else
    call_next_docker "${args[@]}"
  fi
}

# Override commands (and help messages)

function help_short_help {
  echo '  help        Show this message or more detailed command info'
}

function help_long_help {
  cat <<EOF

Usage:  docker help [command]

List all available commands or view detailed usage of a command
EOF
}

function override_help {
  local default_help_message help_function
  default_help_message="$(call_next_docker help "$@")"
  echo "$default_help_message" | head --lines=-1
  echo 'Overwritten commands:'
  for help_function in $(get_short_help_commands | sort); do
    "$help_function"
  done
  echo ''
  echo "$default_help_message" | tail --lines=1 
}

# Override finders/testers (metaprogramming)

function is_override_subcommand {
  local subcommand
  subcommand="$1"
  get_override_subcommands | grep --quiet "^override_$subcommand$"
}

function get_override_subcommands {
  get_function_names | grep '^override_[a-z]*'
}

function get_short_help_commands {
  get_function_names | grep '^help_short_[a-z]*'
}

function get_long_help_commands {
  get_function_names | grep '^help_long_[a-z]*'
}

function get_function_names {
  declare -F | awk '{print $3}'
}

# Utility functions

function contains_help_flag {
  local arg
  for arg in "$@"; do
    if [[ "$arg" == "--help" ]]; then
      return 0
    fi
  done
  return 1
}

function get_dir_name {
  local path
  path="${1:?No path specified.}"
  echo "$(dirname "$(realpath "$path")")"
}

function call_this_docker {
  "$THIS_DOCKER" "$@"
}

# Note: you probably don't need to use this unless you're overriding an existing function
function call_next_docker {
  if [[ "$EUID" -eq 0 ]]; then
    "$NEXT_DOCKER" "$@"
    echo $?
  else
    sudo "$NEXT_DOCKER" "$@"
  fi
}

function echo_tty {
  echo "$@" > /dev/tty
}

function echo_err {
  >&2 echo "$@"
}

main "$@"