#!/usr/bin/env bash

set -e

THIS_DOCKER="$(realpath "$0")"
NEXT_DOCKER="$(which --all docker | grep --after-context=1 "$THIS_DOCKER" | tail -1)"
DEFAULT_COMMAND='help'
TIME_FORMAT='+%Y-%m-%dT%H-%M-%SZ'
TIME_GREP_FORMAT='[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}-[0-9]\{2\}-[0-9]\{2\}Z'

function main {
  local subcommand
  subcommand="$1"
  if [[ "$subcommand" == '' ]]; then
    subcommand="$DEFAULT_COMMAND"
  fi
  if is_override_subcommand "$subcommand"; then
    call_override_command "$subcommand" "${@:2}"
  else
    call_next_docker "$@"
  fi
}

# Override commands (and help messages)

function help_short_autobuild {
  echo '  autobuild   Build an image from a directory containing a Dockerfile'
}
function help_long_autobuild {
  cat <<EOF

Usage:  docker autobuild PATH

Build an image from a directory containing a Dockerfile. The resulting image will be tagged with the name of the containing directory and tagged with the current time.
EOF
}
function override_autobuild {
  local path image_name image_tag_date
  path="$1"
  if [[ "$#" -ne 1 ]]; then
    echo_err '"docker autobuild" requires exactly 1 argument.'
    help_long_autobuild 1>&2
    return 1
  elif [[ ! -d "$path" ]]; then
    echo_err "'$path' is not a directory"
    help_long_autobuild 1>&2
    return 1
  fi
  image_name="$(get_dir_name "$path")"
  image_tag_date="$(get_time)"
  docker build --tag "$image_name:$image_tag_date" --tag "$image_name:latest" "$path"
}

function help_short_autoprune {
  echo '  autoprune   Remove old versions of an image'
}
function help_long_autoprune {
  cat <<EOF

Usage:  docker autoprune PATH [METHOD]

Remove autobuilt images built from PATH (default method: latest).

Available methods:
  a, all          Delete all versions of the image
  o, old          Delete all versions of the image except for the latest (default)
EOF
}
function override_autoprune {
  local path method image_name tags image_name_with_tags
  path="$1"
  method="$2"
  if [[ "$#" -ne 1 ]] && [[ "$#" -ne 2 ]]; then
    echo_err '"docker autoprune" requires 1-2 arguments.'
    help_long_autoprune 1>&2
    return 1
  elif [[ ! -d "$path" ]]; then
    echo_err "'$path' is not a directory"
    help_long_autoprune 1>&2
    return 1
  fi
  image_name="$(get_dir_name "$path")"
  if [[ -z "$method" ]]; then
    method='old'
  fi
  case "$method" in
    a|all)
      mapfile -t tags < <(get_auto_image_tags "$image_name")
      ;;
    o|old)
      mapfile -t tags < <( \
        get_auto_image_tags_with_timestamp "$image_name" | \
        head --lines=-1 \
        )
      ;;
    *)
      echo_err "Unknown method: $method"
      help_long_autoprune 1>&2
      return 1
      ;;
  esac
  if [[ "${#tags[@]}" -eq 0 ]]; then
    echo_err 'No images deleted.'
  else
    mapfile -t image_name_with_tags < <( \
      echo "${tags[@]}" | \
      spaces_to_newlines | \
      xargs --max-lines=1 -I {} echo "$image_name:{}" \
      )
    echo "${image_name_with_tags[@]}" | \
      spaces_to_newlines | \
      xargs docker image rm
  fi
}

function help_short_autorun {
  echo '  autorun     Run the latest image built from an autobuild'
}
function help_long_autorun {
  cat <<EOF

Usage:  docker autorun PATH METHOD [ARG...]

Run a container, where PATH is the directory used to build an image and METHOD is the method used to run the container.

Available methods:
  a, ash          Override the entrypoint to /bin/ash
  b, bash         Override the entrypoint to /bin/bash
  d, detach       Run the container in detached mode
  e, entrypoint   Override the entrypoint to [ARG...]
  s, sh           Override the entrypoint to /bin/sh
  t, tty          Run the container in pseudo-tty mode
EOF
}
function override_autorun {
  local path method args image_name
  path="$1"
  method="$2"
  args=("${@:3}")
  if [[ "$#" -lt 2 ]]; then
    echo_err '"docker autorun" requires at least 2 arguments.'
    help_long_autorun 1>&2
    return 1
  elif [[ ! -d "$path" ]]; then
    echo_err "$path is not a directory"
    return 1
  fi
  image_name="$(get_dir_name "$path")"
  case "$method" in
    a|ash)
      docker run --name "$image_name" --rm --interactive --tty --entrypoint /bin/ash "$image_name"
      ;;
    b|bash)
      docker run --name "$image_name" --rm --interactive --tty --entrypoint /bin/bash "$image_name"
      ;;
    d|detach)
      docker run --name "$image_name" --rm --detach "$image_name"
      ;;
    e|entrypoint)
      docker run --name "$image_name" --rm --interactive --tty --entrypoint "${args[0]}" "$image_name" "${args[@]:1}"
      ;;
    s|sh)
      docker run --name "$image_name" --rm --interactive --tty --entrypoint /bin/sh "$image_name"
      ;;
    t|tty)
      docker run --name "$image_name" --rm --interactive --tty "$image_name"
      ;;
    *)
      echo_err "Unknown method: $method"
      help_long_autorun 1>&2
      return 1
      ;;
  esac
}

function help_short_help {
  echo '  help        Show this message or more detailed command info'
}
function help_long_help {
  cat <<EOF

Usage:  docker help [command]

List all available commands or view detailed usage of a command
EOF
}
function override_help {
  if [[ "$#" -eq 0 ]]; then
    local default_help_message help_function
    default_help_message="$(call_next_docker help "$@")"
    echo "$default_help_message" | head --lines=-1
    echo 'Overwritten commands:'
    for help_function in $(get_short_help_commands | sort); do
      "$help_function"
    done
    echo ''
    echo "$default_help_message" | tail --lines=1 
  elif is_override_subcommand "$1"; then
    "help_long_$1"
  else
    call_next_docker help "$@"
  fi
}

# Override finders/testers (metaprogramming)

function call_override_command {
  local command args
  command="$1"
  args=("${@:2}")
  if contains_help_flag "${args[@]}"; then
    call_this_docker help "$command"
  else
    "override_$subcommand" "${args[@]}"
  fi
}

function is_override_subcommand {
  local subcommand
  subcommand="$1"
  get_override_subcommands | grep --quiet "^override_$subcommand$"
}

function get_override_subcommands {
  get_function_names | grep '^override_[a-z]*'
}

function get_short_help_commands {
  get_function_names | grep '^help_short_[a-z]*'
}

function get_long_help_commands {
  get_function_names | grep '^help_long_[a-z]*'
}

function get_function_names {
  declare -F | awk '{print $3}'
}

# Docker-specifc utility functions

function get_auto_image_tags {
  local image_name
  image_name="${1:?No image name specified.}"
  get_image_tags "$image_name" | grep "^\(\(latest\)\|\($TIME_GREP_FORMAT\)\)$"
}

function get_auto_image_tags_with_timestamp {
  local image_name
  image_name="${1:?No image name specified.}"
  get_image_tags "$image_name" | grep "^$TIME_GREP_FORMAT$"
}

function get_image_tags {
  local image_name
  image_name="${1:?No image name specified.}"
  call_this_docker image ls | awk "\$1 == \"$1\" {print \$2}" | sort
}

function requires_sudo {
  local args
  args=("$@")
  if [[ "${args[0]}" == 'help' ]] || \
    contains_help_flag "${args[@]}"
  then
    return 1
  fi
}

# Utility functions

function call_this_docker {
  main "$@"
}

# Note: you probably don't need to use this unless you're overriding an existing function
function call_next_docker {
  if [[ "$EUID" -ne 0 ]] && requires_sudo "$@"; then
    sudo "$NEXT_DOCKER" "$@"
  else
    "$NEXT_DOCKER" "$@"
  fi
}

function contains_help_flag {
  local arg
  for arg in "$@"; do
    if [[ "$arg" == "--help" ]]; then
      return 0
    fi
  done
  return 1
}

function get_dir_name {
  local path
  path="${1:?No path specified.}"
  basename "$(realpath "$path")"
}

function get_time {
  date --utc "$TIME_FORMAT"
}

function spaces_to_newlines {
  tr ' ' '\n'
}

function echo_tty {
  echo "$@" > /dev/tty
}

function echo_err {
  >&2 echo "$@"
}

main "$@"